name: fish_detection_v2
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
    
  # --- Firebase (Updated for compatibility) ---
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.0
  
  cloudinary_public: ^0.23.0
  
  # --- Fungsionalitas Aplikasi ---
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  http: ^1.2.1

  # --- Izin, Download & Share  ---
  dio: ^5.4.3
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  share_plus: ^9.0.0      
  saver_gallery: ^4.0.1   
  url_launcher: ^6.3.2
  flutter_dotenv: ^6.0.0

dependency_overrides:
  mime: '2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/splash_logo.png"
  min_sdk_android: 21